discord:
  - id: "crawl"
    discord_channel: "crawl"
    discord_username: "test"
    discord_format: "{{data}}"
    discord_webhook_url: "https://discord.com/api/webhooks/1187216684298281070/c5aZMekvNw3U8nUpS5BTtVZHspcEqwVfZCE0N8X72tJeQzvxsqVKWXOxocj_tModedhS"
